import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { validateRequest } from "@/auth/utils";
import Link from "next/link";
import { logout } from "@/auth/action";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await validateRequest();

  return (
    <html lang="en">
      <body className={inter.className}>
        {session.user ? (
          <form action={logout}>
            <button
              className="bg-red-500 text-white px-2 py-1 rounded-md"
              type="submit"
            >
              Logout
            </button>
          </form>
        ) : (
          <Link href="/auth/google/login">Google login</Link>
        )}

        <code>{JSON.stringify(session)}</code>
        {children}
      </body>
    </html>
  );
}
